name: Deploy to SFTP server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List files in workspace
        run: ls -lR

      # Byt till rätt sökväg om dina filer inte ligger i repots rot!
      - name: Copy files via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_SERVER }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          source: "./index.html ./news.json"     # <-- ÄNDRA denna rad om filerna ligger i t.ex. ./public/
          target: "/public_html"                 # <-- ÄNDRA om din webbrotsmapp heter något annat
