name: Deploy to SFTP server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SFTP upload
        uses: presslabs/gitftp-action@v1.5.0
        with:
          url: sftp://${{ secrets.SFTP_SERVER }}
          user: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          local-dir: ./
          remote-dir: /      # byt till rätt mapp om din webbrotsmapp är t.ex. /htdocs
